<div role="main">
	<section class="raise container main" id="drop-zone">
    	<div id="drop-instructions">
			<canvas style="display:none; width:340px; height:315px;"></canvas>
			<video id="user_feed" autoplay controls style="width:340px; height:315px;"></video>
	    	<video width="560" height="315" src="www.youtube.com/embed/PKttjlC0LzU" frameborder="0" allowfullscreen></video>
	    	<script src="getUserMedia.js"></script>

			<div id="container" style="height: 300px; width:900px;"></div>
	    	<script src="./chart.js"></script>
		</div>
	</section>
</div>