<html>
	<head>
		<link rel="stylesheet" type="text/css" href="style.css" media="screen" />
	</head>
	<body>
		<nav class="main-nav right">
			<ul>
				<li><a href="#apps" class="inner-link">Apps</a></li>
		        <li><a href="#pro" class="inner-link">Pro</a></li>
		        <li><a href="/login">Log In</a></li>
				<li><a href="/register?mp_source=1" class="callout">Register</a></li>
			</ul>
		</nav>
		<?php echo $this->layout()->content; ?>
	</body>
</html>